[debug] [2020-03-22T08:09:05.752Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:09:05.754Z] Command:       /Users/Kylie/.nvm/versions/node/v12.1.0/bin/node /Users/Kylie/.nvm/versions/node/v12.1.0/bin/firebase emulators:start --only functions
[debug] [2020-03-22T08:09:05.754Z] CLI Version:   7.15.1
[debug] [2020-03-22T08:09:05.754Z] Platform:      darwin
[debug] [2020-03-22T08:09:05.754Z] Node Version:  v12.1.0
[debug] [2020-03-22T08:09:05.755Z] Time:          Sun Mar 22 2020 08:09:05 GMT+0000 (Greenwich Mean Time)
[debug] [2020-03-22T08:09:05.755Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:09:05.755Z] 
[debug] [2020-03-22T08:09:05.763Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-22T08:09:05.764Z] > authorizing via signed-in user
[info] i  emulators: Starting emulators: functions
[debug] [2020-03-22T08:09:05.791Z] [hub] writing locator at /var/folders/02/vy_dcd8117v5nzbhrvdyvnp00000gn/T/hub-workouts-f919c.json
[info] ✔  hub: emulator hub started at http://localhost:4400
[info] i  emulators: Shutting down emulators.
[info] i  hub: Stopping emulator hub
[debug] [2020-03-22T08:09:05.812Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at Object.<anonymous> (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:162:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-03-22T08:10:57.195Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:10:57.199Z] Command:       /Users/Kylie/.nvm/versions/node/v12.1.0/bin/node /Users/Kylie/.nvm/versions/node/v12.1.0/bin/firebase emulators:start --only functions
[debug] [2020-03-22T08:10:57.199Z] CLI Version:   7.15.1
[debug] [2020-03-22T08:10:57.199Z] Platform:      darwin
[debug] [2020-03-22T08:10:57.199Z] Node Version:  v12.1.0
[debug] [2020-03-22T08:10:57.206Z] Time:          Sun Mar 22 2020 08:10:57 GMT+0000 (Greenwich Mean Time)
[debug] [2020-03-22T08:10:57.206Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:10:57.206Z] 
[debug] [2020-03-22T08:10:57.219Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-22T08:10:57.220Z] > authorizing via signed-in user
[info] i  emulators: Starting emulators: functions
[debug] [2020-03-22T08:10:57.248Z] [hub] writing locator at /var/folders/02/vy_dcd8117v5nzbhrvdyvnp00000gn/T/hub-workouts-f919c.json
[info] ✔  hub: emulator hub started at http://localhost:4400
[info] i  emulators: Shutting down emulators.
[info] i  hub: Stopping emulator hub
[debug] [2020-03-22T08:10:57.257Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at Object.<anonymous> (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:162:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-03-22T08:19:23.127Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:19:23.130Z] Command:       /Users/Kylie/.nvm/versions/node/v12.1.0/bin/node /Users/Kylie/.nvm/versions/node/v12.1.0/bin/firebase emulators:start --only functions
[debug] [2020-03-22T08:19:23.130Z] CLI Version:   7.15.1
[debug] [2020-03-22T08:19:23.130Z] Platform:      darwin
[debug] [2020-03-22T08:19:23.130Z] Node Version:  v12.1.0
[debug] [2020-03-22T08:19:23.137Z] Time:          Sun Mar 22 2020 08:19:23 GMT+0000 (Greenwich Mean Time)
[debug] [2020-03-22T08:19:23.137Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:19:23.138Z] 
[debug] [2020-03-22T08:19:23.154Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-22T08:19:23.155Z] > authorizing via signed-in user
[info] i  emulators: Starting emulators: functions
[debug] [2020-03-22T08:19:23.185Z] [hub] writing locator at /var/folders/02/vy_dcd8117v5nzbhrvdyvnp00000gn/T/hub-workouts-f919c.json
[info] ✔  hub: emulator hub started at http://localhost:4400
[info] i  emulators: Shutting down emulators.
[info] i  hub: Stopping emulator hub
[debug] [2020-03-22T08:19:23.196Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at Object.<anonymous> (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:162:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-03-22T08:20:01.945Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:20:01.948Z] Command:       /Users/Kylie/.nvm/versions/node/v12.1.0/bin/node /Users/Kylie/.nvm/versions/node/v8.15.0/bin/firebase emulators:start --only functions
[debug] [2020-03-22T08:20:01.948Z] CLI Version:   7.15.1
[debug] [2020-03-22T08:20:01.948Z] Platform:      darwin
[debug] [2020-03-22T08:20:01.948Z] Node Version:  v12.1.0
[debug] [2020-03-22T08:20:01.949Z] Time:          Sun Mar 22 2020 08:20:01 GMT+0000 (Greenwich Mean Time)
[debug] [2020-03-22T08:20:01.949Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:20:01.949Z] 
[debug] [2020-03-22T08:20:01.959Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-22T08:20:01.959Z] > authorizing via signed-in user
[info] i  emulators: Starting emulators: functions
[debug] [2020-03-22T08:20:01.985Z] [hub] writing locator at /var/folders/02/vy_dcd8117v5nzbhrvdyvnp00000gn/T/hub-workouts-f919c.json
[info] ✔  hub: emulator hub started at http://localhost:4400
[info] i  emulators: Shutting down emulators.
[info] i  hub: Stopping emulator hub
[debug] [2020-03-22T08:20:01.994Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at Object.<anonymous> (/Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:162:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-03-22T08:20:56.254Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:20:56.257Z] Command:       /Users/Kylie/.nvm/versions/node/v12.1.0/bin/node /Users/Kylie/.nvm/versions/node/v8.15.0/bin/firebase emulators:start --only functions
[debug] [2020-03-22T08:20:56.257Z] CLI Version:   7.15.1
[debug] [2020-03-22T08:20:56.257Z] Platform:      darwin
[debug] [2020-03-22T08:20:56.257Z] Node Version:  v12.1.0
[debug] [2020-03-22T08:20:56.258Z] Time:          Sun Mar 22 2020 08:20:56 GMT+0000 (Greenwich Mean Time)
[debug] [2020-03-22T08:20:56.258Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:20:56.258Z] 
[debug] [2020-03-22T08:20:56.266Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-22T08:20:56.266Z] > authorizing via signed-in user
[info] i  emulators: Starting emulators: functions
[debug] [2020-03-22T08:20:56.292Z] [hub] writing locator at /var/folders/02/vy_dcd8117v5nzbhrvdyvnp00000gn/T/hub-workouts-f919c.json
[info] ✔  hub: emulator hub started at http://localhost:4400
[info] i  emulators: Shutting down emulators.
[info] i  hub: Stopping emulator hub
[debug] [2020-03-22T08:20:56.318Z] Error: Cannot find module '/Users/Kylie/Documents/dev/projects/workouts/server/src/package.json'
Require stack:
- /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js
- /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/controller.js
- /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/commandUtils.js
- /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/commands/emulators-exec.js
- /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/commands/index.js
- /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/index.js
- /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/bin/firebase.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at FunctionsEmulator.<anonymous> (/Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:339:25)
    at Generator.next (<anonymous>)
    at /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:4:12)
    at FunctionsEmulator.askInstallNodeVersion (/Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:338:16)
    at FunctionsEmulator.<anonymous> (/Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:103:42)
    at Generator.next (<anonymous>)
    at /Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:4:12)
    at FunctionsEmulator.start (/Users/Kylie/.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:102:16)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-03-22T08:23:15.912Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:23:15.914Z] Command:       /Users/Kylie/.nvm/versions/node/v12.1.0/bin/node /Users/Kylie/.nvm/versions/node/v12.1.0/bin/firebase serve --only functions
[debug] [2020-03-22T08:23:15.915Z] CLI Version:   7.15.1
[debug] [2020-03-22T08:23:15.915Z] Platform:      darwin
[debug] [2020-03-22T08:23:15.915Z] Node Version:  v12.1.0
[debug] [2020-03-22T08:23:15.916Z] Time:          Sun Mar 22 2020 08:23:15 GMT+0000 (Greenwich Mean Time)
[debug] [2020-03-22T08:23:15.916Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:23:15.916Z] 
[debug] [2020-03-22T08:23:15.925Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-22T08:23:15.925Z] > authorizing via signed-in user
[debug] [2020-03-22T08:23:15.925Z] [iam] checking project workouts-f919c for permissions ["firebase.projects.get"]
[debug] [2020-03-22T08:23:15.927Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2020-03-22T08:23:15.927Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-03-22T08:23:16.099Z] <<< HTTP RESPONSE 200
[debug] [2020-03-22T08:23:16.111Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/workouts-f919c:testIamPermissions  

[debug] [2020-03-22T08:23:16.872Z] <<< HTTP RESPONSE 200
[debug] [2020-03-22T08:23:16.874Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/workouts-f919c  
 
[debug] [2020-03-22T08:23:17.099Z] <<< HTTP RESPONSE 200
[debug] [2020-03-22T08:23:17.109Z] Error: Cannot find module '/Users/Kylie/Documents/dev/projects/workouts/server/src/package.json'
Require stack:
- /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js
- /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/controller.js
- /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/commandUtils.js
- /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/commands/emulators-exec.js
- /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/commands/index.js
- /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/index.js
- /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/bin/firebase.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at FunctionsEmulator.<anonymous> (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:339:25)
    at Generator.next (<anonymous>)
    at /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:4:12)
    at FunctionsEmulator.askInstallNodeVersion (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:338:16)
    at FunctionsEmulator.<anonymous> (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:103:42)
    at Generator.next (<anonymous>)
    at /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:4:12)
    at FunctionsEmulator.start (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:102:16)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-03-22T08:24:06.839Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:24:06.841Z] Command:       /Users/Kylie/.nvm/versions/node/v12.1.0/bin/node /Users/Kylie/.nvm/versions/node/v12.1.0/bin/firebase serve --only functions
[debug] [2020-03-22T08:24:06.842Z] CLI Version:   7.15.1
[debug] [2020-03-22T08:24:06.842Z] Platform:      darwin
[debug] [2020-03-22T08:24:06.842Z] Node Version:  v12.1.0
[debug] [2020-03-22T08:24:06.843Z] Time:          Sun Mar 22 2020 08:24:06 GMT+0000 (Greenwich Mean Time)
[debug] [2020-03-22T08:24:06.843Z] ----------------------------------------------------------------------
[debug] [2020-03-22T08:24:06.843Z] 
[debug] [2020-03-22T08:24:06.851Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-22T08:24:06.852Z] > authorizing via signed-in user
[debug] [2020-03-22T08:24:06.852Z] [iam] checking project workouts-f919c for permissions ["firebase.projects.get"]
[debug] [2020-03-22T08:24:06.854Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/workouts-f919c:testIamPermissions  

[debug] [2020-03-22T08:24:07.667Z] <<< HTTP RESPONSE 200
[debug] [2020-03-22T08:24:07.669Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/workouts-f919c  
 
[debug] [2020-03-22T08:24:07.879Z] <<< HTTP RESPONSE 200
[debug] [2020-03-22T08:24:07.895Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at Object.<anonymous> (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/serve/functions.js:21:39)
    at Generator.next (<anonymous>)
    at /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/serve/functions.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/serve/functions.js:4:12)
    at Object.start (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/serve/functions.js:19:16)
    at /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/serve/index.js:25:40
    at arrayMap (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/serve/index.js:24:29
    at Generator.next (<anonymous>)
    at /Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/serve/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Kylie/.nvm/versions/node/v12.1.0/lib/node_modules/firebase-tools/lib/serve/index.js:4:12)
[error] 
[error] Error: An unexpected error has occurred.
